[package]
name = "euklidische_algo"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Implementation of the euklidish algorithm to find the "



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
